[package]
name = "axfs-ng-vfs"
version = "0.1.0"
edition = "2024"
authors = ["Mivik <mivikq@gmail.com>"]

[lib]

[dependencies]
axerrno = { git = "https://github.com/Starry-Mix-THU/axerrno.git", rev = "f5d8f86" }
bitflags = "2.9.0"
inherit-methods-macro = "0.1.0"
lock_api = "0.4.12"
log = "=0.4.21"
