[package]
name = "axfs-ng-vfs"
version = "0.1.0"
edition = "2024"
authors = ["Mivik <mivikq@gmail.com>"]

[lib]

[dependencies]
axerrno = { git = "https://github.com/Starry-Mix-THU/axerrno.git", rev = "f5d8f86" }
axio = { git = "https://github.com/Starry-Mix-THU/axio.git", rev = "a069a3d" }
bitflags = "2.9.0"
hashbrown = "0.15.4"
inherit-methods-macro = "0.1.0"
log = "=0.4.21"
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }
